// Auto-generated by OpenLane
module rcAdder(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input[15:0] a_i,
  input[15:0] b_i,
  output[15:0] sum_o,
  output carry_o
);
endmodule
