// Auto-generated by OpenLane
module rcAdder(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input[3:0] a_i,
  input[3:0] b_i,
  output[3:0] sum_o,
  output carry_o
);
endmodule
